HOST = "158.109.9.60"

CONTEXT_BROKER_PORT = 1026
IMAGE_STORAGE_API_PORT = 9001
FACE_RECOGNITION_API_PORT = 9002
FACE_DETECTION_API_PORT = 9007

LARGE_FILE_BSIZE = 400e6

IMG_FACES_PATH = "../../../data/samples/images/faces/celeb/ben_mad_min_jer.png"
IMG_FACES_ID_PATH = "_IMG_FACES_ID"