face_detector:
  model_name: face_detector_retinaface
  params:
    weights_path: ../../../data/models/face_detector_retinaface/Resnet50_Final.pth
    model_name: resnet50
    confidence_threshold: 0.7
    landmarks: False
    nms_threshold: 0.4
    use_cuda: False

context_broker:
  host: 192.168.0.100
  port: 1026
  # URI where notifications will be sent
  notification_uri: http://192.168.0.100:8080/ngsi-ld/v1/notify

api:
  host: 0.0.0.0
  port: 8080
  
  # List of origins that should be permitted to make cross-origin requests.
  allowed_origins: []
  
  # If the images are stored locally and can be accessed by their path.
  local_image_storage: False

subscriptions:
  - entity_type: Image
    watched_attributes: ["purpose"]
    query: "purpose==%22FaceDetection%22"

visualization:
  image_width: 800
