common-host: &common-host
  127.0.0.1

pagination_limit: &pagination_limit
  30

context_broker_links: &context_broker_links
  True

context_broker:
  host: *common-host
  port: 1026

image_storage: &image_storage
  host: *common-host
  port: 9001
  url_path: /

projects:
  - name: Context Broker
    port: 1026
    host: *common-host
    url_path: /
    template: ContextBrokerTemplate
    refresh_rate: 10 # seconds
  - name: Image Storage
    template: ImageStorageTemplate
    pagination_limit: *pagination_limit
    context_broker_links: *context_broker_links
    <<: *image_storage
  - name: Face Detection
    port: 9007
    host: *common-host
    url_path: /
    template: SimplePredict
  - name: Face Recognition
    port: 9002
    host: *common-host
    url_path: /
    template: SimplePredict # TODO: Change to FaceRecognition
  - name: Face Emotions
    port: 9004
    host: *common-host
    url_path: /
    template: SimplePredict
  - name: Age Gender
    port: 9003
    host: *common-host
    url_path: /
    description_path: res/descriptions/age_gender.txt
    template: SimplePredict
  - name: Instance Segmentation
    port: 9005
    host: *common-host
    url_path: /
    template: SimplePredict
  - name: Keypoints
    port: 9006
    host: *common-host
    url_path: /
    template: SimplePredict
