common-host: &common-host
  158.109.9.60

image_storage: &image_storage
  host: *common-host
  port: 9001
  url_path: /

projects:
  - name: Image Storage
    template: SimplePredict
    <<: *image_storage
  - name: Face Detection
    port: 9007
    host: *common-host
    url_path: /
    template: SimplePredict
  - name: Age Gender
    port: 9003
    host: *common-host
    url_path: /
    template: SimplePredict
  - name: Instance Segmentation
    port: 9005
    host: *common-host
    url_path: /
    template: SimplePredict