common-host: &common-host
  192.168.0.100

image_storage: &image_storage
  host: *common-host
  port: 9001
  url_path: /

projects:
  - name: Image Storage
    template: SimplePredict
    <<: *image_storage
  - name: Face Detection
    port: 9002
    host: *common-host
    url_path: /
    template: SimplePredict